---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/accrawho/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp /css $DEPLOYPATH
    - /bin/cp /js $DEPLOYPATH
    - /bin/cp /img $DEPLOYPATH