---
deployment:
  tasks:
    - export DEPLOYPATH=/home/opencour/public_html/accrawho/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp mail.php $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH